export const architects = [
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    title: "Principal Architect",
    location: "San Francisco, CA",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    rating: 4.9,
    reviewCount: 127,
    projectCount: 48,
    specialties: ["Modern Residential", "Sustainable Design", "Interior"],
    bio: "Award-winning architect with 15+ years of experience in sustainable residential design. My philosophy centers on creating spaces that harmonize with their environment while meeting the unique needs of each client.",
    featured: true,
    hourlyRate: 250,
    minimumProjectBudget: 75000,
    email: "sarah.chen@architure.com",
    phone: "+1 (415) 555-0123",
    social: {
      instagram: "https://instagram.com/sarahchenarch",
      linkedin: "https://linkedin.com/in/sarahchen",
      website: "https://sarahchenarchitecture.com",
      twitter: "https://twitter.com/sarahchenarch",
    },
  },
  {
    id: "marcus-weber",
    name: "Marcus Weber",
    title: "Design Director",
    location: "New York, NY",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    rating: 4.8,
    reviewCount: 89,
    projectCount: 62,
    specialties: ["Commercial", "Urban Planning", "Mixed-Use"],
    bio: "Specializing in commercial and mixed-use developments, I bring a unique perspective that balances aesthetic innovation with functional excellence.",
    featured: true,
    hourlyRate: 300,
    minimumProjectBudget: 150000,
    email: "marcus.weber@architure.com",
    phone: "+1 (212) 555-0456",
    social: {
      instagram: "https://instagram.com/marcusweberdesign",
      linkedin: "https://linkedin.com/in/marcusweber",
      website: "https://marcusweberdesign.com",
      twitter: "https://twitter.com/marcusweber",
    },
  },
  {
    id: "elena-rodriguez",
    name: "Elena Rodriguez",
    title: "Senior Architect",
    location: "Los Angeles, CA",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    rating: 4.9,
    reviewCount: 156,
    projectCount: 73,
    specialties: ["Luxury Residential", "Renovation", "Historic Preservation"],
    bio: "With a passion for blending old and new, I specialize in thoughtful renovations and luxury residential projects that honor architectural heritage while embracing modern living.",
    featured: true,
    hourlyRate: 275,
    minimumProjectBudget: 100000,
    email: "elena.rodriguez@architure.com",
    phone: "+1 (310) 555-0789",
    social: {
      instagram: "https://instagram.com/elenarodriguezarch",
      linkedin: "https://linkedin.com/in/elenarod",
      website: "https://elenaarchitecture.com",
      twitter: "https://twitter.com/elenarod",
    },
  },
  {
    id: "james-okonkwo",
    name: "James Okonkwo",
    title: "Founding Partner",
    location: "Chicago, IL",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    rating: 4.7,
    reviewCount: 94,
    projectCount: 55,
    specialties: ["Public Buildings", "Educational", "Community Spaces"],
    bio: "Dedicated to creating spaces that serve communities, my work focuses on public buildings, educational facilities, and spaces that bring people together.",
    featured: false,
    hourlyRate: 225,
    minimumProjectBudget: 125000,
    email: "james.okonkwo@architure.com",
    phone: "+1 (312) 555-0321",
    social: {
      instagram: "https://instagram.com/jamesokonkwo",
      linkedin: "https://linkedin.com/in/james-okonkwo",
      website: "https://jamesokonkwoarch.com",
      twitter: "https://twitter.com/jokonkwo",
    },
  },
  {
    id: "ana-silva",
    name: "Ana Silva",
    title: "Lead Architect",
    location: "Miami, FL",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec8?w=800&h=600&fit=crop",
    rating: 4.8,
    reviewCount: 78,
    projectCount: 41,
    specialties: ["Coastal Architecture", "Resort Design", "Landscape"],
    bio: "Inspired by coastal landscapes and tropical environments, I create architecture that celebrates natural light, ocean views, and indoor-outdoor living.",
    featured: false,
    hourlyRate: 260,
    minimumProjectBudget: 85000,
    email: "ana.silva@architure.com",
    phone: "+1 (305) 555-0654",
    social: {
      instagram: "https://instagram.com/anasilvaarch",
      linkedin: "https://linkedin.com/in/ana-silva",
      website: "https://anasilva.com",
      twitter: "https://twitter.com/anasilva",
    },
  },
  {
    id: "david-kim",
    name: "David Kim",
    title: "Principal Designer",
    location: "Seattle, WA",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    rating: 4.9,
    reviewCount: 112,
    projectCount: 67,
    specialties: ["Tech Offices", "Minimalist", "Smart Homes"],
    bio: "At the intersection of technology and design, I create spaces that embrace innovation while maintaining warmth and human connection.",
    featured: true,
    hourlyRate: 280,
    minimumProjectBudget: 95000,
    email: "david.kim@architure.com",
    phone: "+1 (206) 555-0987",
    social: {
      instagram: "https://instagram.com/davidkimarch",
      linkedin: "https://linkedin.com/in/david-kim",
      website: "https://davidkimdesign.com",
      twitter: "https://twitter.com/davidkim",
    },
  },
]

export const blogPosts = [
  {
    id: "blog-1",
    title: "The Future of Sustainable Architecture",
    excerpt: "Exploring how modern architects can integrate sustainable practices without compromising on aesthetics and functionality.",
    content: "Sustainable architecture is no longer just a trend—it's a necessity. As we face unprecedented environmental challenges, architects have a responsibility to pioneer designs that minimize ecological impact while creating beautiful, functional spaces.\n\nKey areas to focus on:\n\n1. Material Selection\nChoosing locally-sourced, renewable materials reduces carbon footprint and supports local economies. Reclaimed wood, recycled steel, and sustainable concrete alternatives are becoming standard in modern projects.\n\n2. Energy Efficiency\nPassive solar design, proper insulation, and smart building systems can reduce energy consumption by up to 50%. Integration of renewable energy sources like solar panels and wind turbines is now more cost-effective than ever.\n\n3. Water Management\nGreen roofs, rainwater harvesting systems, and greywater recycling create self-sufficient buildings that minimize environmental impact.\n\n4. Biophilic Design\nIncorporating natural elements and nature views into built spaces improves occupant well-being while connecting buildings to their natural surroundings.\n\nThe future of architecture lies in our ability to balance innovation with responsibility. By embracing sustainability, we create spaces that benefit both people and the planet.",
    author: "Sarah Chen",
    authorId: "sarah-chen",
    authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    publishedDate: "2024-01-22",
    status: "approved",
    category: "Sustainability",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    likes: 342,
    comments: [
      {
        id: "comment-1",
        author: "John Wilson",
        content: "Excellent perspective on sustainable design. I've been implementing these principles in my recent projects with great success.",
        date: "2024-01-23",
        likes: 12,
      },
      {
        id: "comment-2",
        author: "Maria Garcia",
        content: "The section on biophilic design really resonated with me. Looking forward to more on this topic.",
        date: "2024-01-24",
        likes: 8,
      },
    ],
  },
  {
    id: "blog-2",
    title: "Designing Spaces for Remote Work",
    excerpt: "How to create home offices that boost productivity and well-being in the modern remote work era.",
    content: "The shift to remote work has transformed how we think about home spaces. No longer just a guest room, the home office has become a critical component of modern living.\n\nEssential Elements for a Productive Home Office:\n\n1. Natural Light\nPosition your desk near windows to maximize natural light. This reduces eye strain, improves mood, and boosts productivity.\n\n2. Ergonomic Design\nInvest in quality furniture that supports proper posture. An ergonomic chair, adjustable desk, and monitor stand are essential.\n\n3. Noise Isolation\nIncorporate sound-dampening materials to create a quiet workspace. Consider acoustic panels and thick carpeting.\n\n4. Storage Solutions\nClean, organized spaces reduce mental clutter. Built-in shelving and filing systems keep everything accessible.\n\n5. Break Spaces\nDesign small areas for breaks away from your desk. A coffee nook or reading corner helps refresh the mind.\n\nThe home office should enhance your quality of life, not just serve as a workspace. Thoughtful design makes all the difference.",
    author: "David Kim",
    authorId: "david-kim",
    authorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    publishedDate: "2024-01-20",
    status: "approved",
    category: "Interior Design",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    likes: 289,
    comments: [
      {
        id: "comment-3",
        author: "Alex Thompson",
        content: "Great tips! I just redesigned my home office and these principles really helped.",
        date: "2024-01-21",
        likes: 15,
      },
    ],
  },
  {
    id: "blog-3",
    title: "Historic Preservation: Honoring the Past While Embracing the Future",
    excerpt: "Best practices for renovating historic buildings while maintaining their architectural integrity.",
    content: "Historic preservation is one of the most challenging and rewarding aspects of architecture. It requires balancing respect for original design with modern functionality and comfort.\n\nKey Principles:\n\n1. Research Thoroughly\nUnderstand the building's history, original materials, and architectural style. Documentation is crucial before any work begins.\n\n2. Preserve Original Features\nRetain character-defining features whenever possible. Original woodwork, hardware, and materials tell the building's story.\n\n3. Use Compatible Materials\nWhen replacement is necessary, use materials that match the original in composition, appearance, and durability.\n\n4. Modern Systems, Hidden Integration\nElectrical, plumbing, and HVAC systems can be integrated unobtrusively within walls and existing spaces.\n\n5. Respect the Original Design Intent\nEven when adding modern elements, they should complement rather than compete with the original design.\n\nSuccessful historic preservation allows communities to maintain their cultural heritage while enjoying modern living standards. It's a delicate balance that requires expertise, sensitivity, and creativity.",
    author: "Elena Rodriguez",
    authorId: "elena-rodriguez",
    authorImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    publishedDate: "2024-01-18",
    status: "approved",
    category: "Renovation",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    likes: 198,
    comments: [],
  },
  {
    id: "blog-4",
    title: "Urban Planning for Livable Cities",
    excerpt: "Creating urban spaces that prioritize community, sustainability, and quality of life.",
    content: "Modern cities face unprecedented challenges. How do we create urban environments that are sustainable, equitable, and vibrant?\n\nPriorities for Urban Design:\n\n1. Mixed-Use Development\nCombining residential, commercial, and recreational spaces reduces car dependency and creates vibrant neighborhoods.\n\n2. Public Transportation\nAccessible, efficient public transit is fundamental to reducing congestion and emissions.\n\n3. Green Spaces\nParks, gardens, and green corridors improve air quality, provide recreation, and enhance mental health.\n\n4. Walkability\nStreets designed for pedestrians create safer, more social communities.\n\n5. Affordable Housing\nIncluding diverse housing types ensures cities remain accessible to people of all income levels.\n\nThe cities we build today will shape the communities of tomorrow. Thoughtful urban planning can create spaces where people thrive.",
    author: "Marcus Weber",
    authorId: "marcus-weber",
    authorImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    publishedDate: "2024-01-15",
    status: "approved",
    category: "Urban Planning",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    likes: 412,
    comments: [
      {
        id: "comment-4",
        author: "Lisa Chen",
        content: "Brilliant insights on mixed-use development. This is exactly what our city needs.",
        date: "2024-01-16",
        likes: 21,
      },
      {
        id: "comment-5",
        author: "Robert Kim",
        content: "The walkability section resonates deeply. Car-centric cities are a thing of the past.",
        date: "2024-01-17",
        likes: 18,
      },
    ],
  },
  {
    id: "blog-5",
    title: "Coastal Architecture: Designing for Beauty and Resilience",
    excerpt: "Creating stunning coastal properties that withstand environmental challenges.",
    content: "Coastal architecture presents unique opportunities and challenges. How do we create beautiful homes and structures that respect and withstand the coastal environment?\n\nDesign Considerations:\n\n1. Climate Resilience\nElevated structures, impact-resistant materials, and proper drainage protect against storms and flooding.\n\n2. Salt Air Protection\nSpecialized coatings and materials resist corrosion from salt spray and humidity.\n\n3. Views and Privacy\nLarge windows capture ocean views while strategic landscaping provides privacy and windbreaks.\n\n4. Sustainable Practices\nRainwater collection, native plantings, and renewable energy are essential in sensitive coastal areas.\n\n5. Integration with Landscape\nArchitecture should enhance rather than dominate the natural coastal landscape.\n\nCasual elegance, durability, and environmental stewardship define the best coastal architecture.",
    author: "Ana Silva",
    authorId: "ana-silva",
    authorImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    publishedDate: "2024-01-12",
    status: "approved",
    category: "Coastal Design",
    image: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec8?w=800&h=600&fit=crop",
    likes: 267,
    comments: [],
  },
  {
    id: "blog-6",
    title: "The Impact of Lighting Design on Spaces",
    excerpt: "How strategic lighting transforms architecture and enhances user experience.",
    content: "Lighting is often overlooked, but it's fundamental to how we experience spaces. Strategic lighting design can transform an ordinary room into something extraordinary.\n\nLighting Strategies:\n\n1. Natural Light First\nMaximize natural light through strategic window placement and skylights. Natural light improves mood and reduces energy costs.\n\n2. Layered Lighting\nCombine ambient, task, and accent lighting for flexibility and visual interest.\n\n3. Color Temperature\nWarm light creates intimacy; cool light energizes. Match color temperature to room purpose.\n\n4. Avoid Glare\nProper shading and diffusion prevent eye strain and discomfort.\n\n5. Smart Controls\nProgrammable lighting adapts to time of day and activities, improving energy efficiency.\n\nLighting is the soul of architecture. When done well, it's invisible—when done poorly, it's all you notice.",
    author: "Sarah Chen",
    authorId: "sarah-chen",
    authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    publishedDate: "2024-01-08",
    status: "approved",
    category: "Design Theory",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    likes: 356,
    comments: [
      {
        id: "comment-6",
        author: "Emma White",
        content: "Finally someone discussing lighting design properly! This should be taught more in architecture schools.",
        date: "2024-01-09",
        likes: 24,
      },
    ],
  },
]

export const portfolioProjects = [
  {
    id: "coastal-retreat",
    title: "Coastal Retreat",
    architect: "Sarah Chen",
    architectId: "sarah-chen",
    category: "Residential",
    location: "Malibu, CA",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    likes: 1284,
    views: 15420,
    description: "A stunning oceanfront residence that seamlessly blends indoor and outdoor living spaces.",
  },
  {
    id: "urban-loft",
    title: "Urban Loft Conversion",
    architect: "Marcus Weber",
    architectId: "marcus-weber",
    category: "Interior",
    location: "Brooklyn, NY",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    likes: 892,
    views: 11230,
    description: "An industrial warehouse transformed into a sophisticated living space with modern amenities.",
  },
  {
    id: "hillside-villa",
    title: "Hillside Villa",
    architect: "Elena Rodriguez",
    architectId: "elena-rodriguez",
    category: "Residential",
    location: "Los Angeles, CA",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    likes: 2156,
    views: 28940,
    description: "A luxurious hillside residence featuring panoramic views and sustainable design elements.",
  },
  {
    id: "tech-campus",
    title: "Innovation Campus",
    architect: "David Kim",
    architectId: "david-kim",
    category: "Commercial",
    location: "Seattle, WA",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    likes: 1567,
    views: 19870,
    description: "A forward-thinking tech campus designed to foster collaboration and innovation.",
  },
  {
    id: "community-center",
    title: "Community Arts Center",
    architect: "James Okonkwo",
    architectId: "james-okonkwo",
    category: "Public",
    location: "Chicago, IL",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    likes: 743,
    views: 8920,
    description: "A vibrant community space that brings together art, education, and social gathering.",
  },
  {
    id: "beach-house",
    title: "Tropical Beach House",
    architect: "Ana Silva",
    architectId: "ana-silva",
    category: "Residential",
    location: "Miami, FL",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec8?w=800&h=600&fit=crop",
    likes: 1823,
    views: 22450,
    description: "A tropical paradise featuring open-air living and seamless beach access.",
  },
  {
    id: "boutique-hotel",
    title: "Boutique Hotel",
    architect: "Elena Rodriguez",
    architectId: "elena-rodriguez",
    category: "Commercial",
    location: "Santa Barbara, CA",
    year: "2023",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
    likes: 1456,
    views: 17890,
    description: "A boutique hotel that captures the essence of California coastal elegance.",
  },
  {
    id: "minimalist-home",
    title: "Minimalist Sanctuary",
    architect: "David Kim",
    architectId: "david-kim",
    category: "Residential",
    location: "Portland, OR",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
    likes: 2089,
    views: 25670,
    description: "A serene minimalist home designed for mindful living and connection with nature.",
  },
  {
    id: "garden-renovation",
    title: "Garden Terrace House",
    architect: "Sarah Chen",
    architectId: "sarah-chen",
    category: "Renovation",
    location: "San Francisco, CA",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop",
    likes: 967,
    views: 12340,
    description: "A thoughtful renovation that transforms a Victorian home with modern garden spaces.",
  },
  {
    id: "lakeside-cabin",
    title: "Lakeside Cabin",
    architect: "Marcus Weber",
    architectId: "marcus-weber",
    category: "Residential",
    location: "Lake Tahoe, CA",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    likes: 1678,
    views: 20150,
    description: "A modern interpretation of the classic mountain cabin with stunning lake views.",
  },
  {
    id: "urban-park",
    title: "Urban Pocket Park",
    architect: "James Okonkwo",
    architectId: "james-okonkwo",
    category: "Landscape",
    location: "Chicago, IL",
    year: "2024",
    image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&h=600&fit=crop",
    likes: 534,
    views: 6780,
    description: "A small urban park that provides a green oasis in a dense city neighborhood.",
  },
  {
    id: "spa-retreat",
    title: "Wellness Spa Resort",
    architect: "Ana Silva",
    architectId: "ana-silva",
    category: "Commercial",
    location: "Palm Beach, FL",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&h=600&fit=crop",
    likes: 1234,
    views: 15670,
    description: "A luxury wellness spa designed to promote relaxation and rejuvenation.",
  },
]

export const architectBids = [
  {
    id: "arch-bid-1",
    projectId: "bid-1",
    architectId: "sarah-chen",
    architect: "Sarah Chen",
    architectImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    proposedBudget: "$950,000",
    proposedTimeline: "14 months",
    submittedDate: "2024-01-18",
    status: "Pending",
    message: "I would love to design your modern family home. With my experience in sustainable residential design, I can create a space that balances modern aesthetics with eco-friendly features. My approach would include passive solar design, natural ventilation, and high-quality materials.",
    rating: 4.9,
    projectsCompleted: 48,
  },
  {
    id: "arch-bid-2",
    projectId: "bid-1",
    architectId: "david-kim",
    architect: "David Kim",
    architectImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    proposedBudget: "$1,050,000",
    proposedTimeline: "16 months",
    submittedDate: "2024-01-20",
    status: "Pending",
    message: "Your project aligns perfectly with my expertise in smart home integration and minimalist design. I envision a home that seamlessly integrates technology while maintaining warmth and connection to nature.",
    rating: 4.9,
    projectsCompleted: 67,
  },
  {
    id: "arch-bid-3",
    projectId: "bid-1",
    architectId: "marcus-weber",
    architect: "Marcus Weber",
    architectImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    proposedBudget: "$1,100,000",
    proposedTimeline: "15 months",
    submittedDate: "2024-01-19",
    status: "Pending",
    message: "I bring extensive experience in creating functional yet beautiful living spaces. My design would focus on flexible spaces that grow with your family while incorporating the latest in sustainable building practices.",
    rating: 4.8,
    projectsCompleted: 62,
  },
  {
    id: "arch-bid-4",
    projectId: "bid-2",
    architectId: "elena-rodriguez",
    architect: "Elena Rodriguez",
    architectImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    proposedBudget: "$195,000",
    proposedTimeline: "5 months",
    submittedDate: "2024-01-22",
    status: "Pending",
    message: "I specialize in luxury hospitality design and have completed several award-winning restaurant projects. My coastal modern approach would create an unforgettable dining atmosphere.",
    rating: 4.9,
    projectsCompleted: 73,
  },
  {
    id: "arch-bid-5",
    projectId: "bid-2",
    architectId: "ana-silva",
    architect: "Ana Silva",
    architectImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    proposedBudget: "$210,000",
    proposedTimeline: "5 months",
    submittedDate: "2024-01-23",
    status: "Pending",
    message: "Coastal architecture is my passion. I would bring a fresh perspective to your seafood restaurant with natural materials, ocean-inspired colors, and thoughtful lighting design.",
    rating: 4.8,
    projectsCompleted: 41,
  },
  {
    id: "arch-bid-6",
    projectId: "bid-3",
    architectId: "elena-rodriguez",
    architect: "Elena Rodriguez",
    architectImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    proposedBudget: "$620,000",
    proposedTimeline: "10 months",
    submittedDate: "2024-01-15",
    status: "Shortlisted",
    message: "Historic preservation is a core part of my practice. I have successfully completed numerous projects that honor original architectural details while seamlessly integrating modern amenities.",
    rating: 4.9,
    projectsCompleted: 73,
  },
  {
    id: "arch-bid-7",
    projectId: "bid-4",
    architectId: "david-kim",
    architect: "David Kim",
    architectImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    proposedBudget: "$380,000",
    proposedTimeline: "7 months",
    submittedDate: "2024-01-24",
    status: "Pending",
    message: "Tech office design is my specialty. I understand the unique needs of creative agencies and would design spaces that foster collaboration, focus, and innovation.",
    rating: 4.9,
    projectsCompleted: 67,
  },
  {
    id: "arch-bid-8",
    projectId: "bid-5",
    architectId: "ana-silva",
    architect: "Ana Silva",
    architectImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    proposedBudget: "$1,750,000",
    proposedTimeline: "20 months",
    submittedDate: "2024-01-25",
    status: "Pending",
    message: "Beachfront luxury homes are my expertise. I would create a stunning retreat that maximizes ocean views while ensuring privacy and sustainability.",
    rating: 4.8,
    projectsCompleted: 41,
  },
  {
    id: "arch-bid-9",
    projectId: "bid-5",
    architectId: "sarah-chen",
    architect: "Sarah Chen",
    architectImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    proposedBudget: "$1,850,000",
    proposedTimeline: "22 months",
    submittedDate: "2024-01-26",
    status: "Pending",
    message: "Sustainable coastal design is at the heart of my practice. I would design a home that respects the oceanfront environment while delivering the luxury and comfort you desire.",
    rating: 4.9,
    projectsCompleted: 48,
  },
]

export const projectBids = [
  {
    id: "bid-1",
    projectTitle: "Modern Family Home",
    projectType: "Residential",
    client: "Thompson Family",
    budget: "$850,000 - $1,200,000",
    timeline: "12-18 months",
    location: "Palo Alto, CA",
    description: "Looking for an architect to design a 4-bedroom modern family home with sustainable features, home office space, and indoor-outdoor living areas.",
    postedDate: "2024-01-15",
    deadline: "2024-02-15",
    bidsReceived: 8,
    status: "Open",
  },
  {
    id: "bid-2",
    projectTitle: "Restaurant Interior Redesign",
    projectType: "Commercial",
    client: "Blue Ocean Hospitality",
    budget: "$150,000 - $250,000",
    timeline: "4-6 months",
    location: "San Diego, CA",
    description: "Complete interior redesign of a 3,500 sq ft upscale seafood restaurant. Looking for a fresh, coastal modern aesthetic.",
    postedDate: "2024-01-18",
    deadline: "2024-02-20",
    bidsReceived: 12,
    status: "Open",
  },
  {
    id: "bid-3",
    projectTitle: "Historic Home Renovation",
    projectType: "Renovation",
    client: "Private Client",
    budget: "$500,000 - $750,000",
    timeline: "8-12 months",
    location: "Boston, MA",
    description: "Seeking an architect experienced in historic preservation to renovate a 1920s colonial home while adding modern amenities.",
    postedDate: "2024-01-10",
    deadline: "2024-02-10",
    bidsReceived: 5,
    status: "Under Review",
  },
  {
    id: "bid-4",
    projectTitle: "Boutique Office Space",
    projectType: "Commercial",
    client: "Creative Studios Inc.",
    budget: "$300,000 - $450,000",
    timeline: "6-9 months",
    location: "Austin, TX",
    description: "Design a creative office space for a 50-person design agency. Focus on collaboration areas, quiet zones, and unique meeting spaces.",
    postedDate: "2024-01-20",
    deadline: "2024-02-25",
    bidsReceived: 15,
    status: "Open",
  },
  {
    id: "bid-5",
    projectTitle: "Beach Vacation Home",
    projectType: "Residential",
    client: "Martinez Family",
    budget: "$1,500,000 - $2,000,000",
    timeline: "18-24 months",
    location: "Malibu, CA",
    description: "Luxury beachfront vacation home with 5 bedrooms, infinity pool, and guest house. Sustainability and ocean views are priorities.",
    postedDate: "2024-01-22",
    deadline: "2024-03-01",
    bidsReceived: 20,
    status: "Open",
  },
]

export const vacancies = [
  {
    id: "vacancy-1",
    title: "Senior Architect",
    company: "Chen Architecture Studio",
    location: "San Francisco, CA",
    salaryMin: 120000,
    salaryMax: 160000,
    jobType: "full-time",
    description: "We are looking for a Senior Architect with 8+ years of experience in sustainable residential design. You will lead a team of 4 designers and manage projects from concept to completion.\n\nResponsibilities:\n- Lead design development for residential projects\n- Manage client relationships and presentations\n- Mentor junior architects and interns\n- Oversee construction documentation",
    requirements: "- Licensed Architect (RA) required\n- 8+ years of professional experience\n- Proficiency in Revit, AutoCAD, and SketchUp\n- LEED accreditation preferred\n- Strong portfolio of residential projects",
    applyUrl: "https://example.com/careers/senior-architect",
    applyEmail: "careers@chenarchitecture.com",
    status: "approved",
    createdAt: "2024-01-20",
  },
  {
    id: "vacancy-2",
    title: "Interior Design Associate",
    company: "Weber Design Group",
    location: "New York, NY",
    salaryMin: 75000,
    salaryMax: 95000,
    jobType: "full-time",
    description: "Join our award-winning interior design team in Manhattan. We specialize in high-end commercial interiors for tech companies and creative agencies.\n\nYou'll work alongside our Design Director to create innovative workspace solutions that inspire creativity and collaboration.",
    requirements: "- Bachelor's degree in Interior Design or Architecture\n- 3-5 years of commercial interior design experience\n- Expertise in 3ds Max, V-Ray, and Adobe Creative Suite\n- Knowledge of building codes and ADA compliance",
    applyEmail: "hr@weberdesign.com",
    status: "approved",
    createdAt: "2024-01-18",
  },
  {
    id: "vacancy-3",
    title: "Architecture Intern",
    company: "Rodriguez & Partners",
    location: "Los Angeles, CA",
    salaryMin: 45000,
    salaryMax: 55000,
    jobType: "internship",
    description: "6-month paid internship opportunity for architecture students or recent graduates. Gain hands-on experience in luxury residential design and historic preservation projects.\n\nYou'll be exposed to all phases of design, from schematic concepts to construction administration.",
    requirements: "- Currently enrolled in or recently graduated from an accredited Architecture program\n- Strong hand-sketching and digital rendering skills\n- Familiarity with Revit and Rhino\n- Passion for historic preservation",
    applyUrl: "https://example.com/internships",
    status: "approved",
    createdAt: "2024-01-15",
  },
  {
    id: "vacancy-4",
    title: "Freelance Landscape Architect",
    company: "Silva Coastal Design",
    location: "Miami, FL (Remote OK)",
    salaryMin: 80,
    salaryMax: 120,
    jobType: "contract",
    description: "We need a freelance landscape architect for a luxury resort project in South Florida. The contract is for approximately 4 months with possibility of extension.\n\nThe project involves designing outdoor spaces, pool areas, and tropical gardens for a boutique hotel.",
    requirements: "- Licensed Landscape Architect\n- Experience with tropical/coastal landscape design\n- Portfolio of resort or hospitality projects\n- Available to start within 2 weeks",
    applyEmail: "projects@silvacoastal.com",
    status: "approved",
    createdAt: "2024-01-12",
  },
]

