export const architects = [
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    title: "Principal Architect",
    location: "San Francisco, CA",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    rating: 4.9,
    reviewCount: 127,
    projectCount: 48,
    specialties: ["Modern Residential", "Sustainable Design", "Interior"],
    bio: "Award-winning architect with 15+ years of experience in sustainable residential design. My philosophy centers on creating spaces that harmonize with their environment while meeting the unique needs of each client.",
    featured: true,
  },
  {
    id: "marcus-weber",
    name: "Marcus Weber",
    title: "Design Director",
    location: "New York, NY",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    rating: 4.8,
    reviewCount: 89,
    projectCount: 62,
    specialties: ["Commercial", "Urban Planning", "Mixed-Use"],
    bio: "Specializing in commercial and mixed-use developments, I bring a unique perspective that balances aesthetic innovation with functional excellence.",
    featured: true,
  },
  {
    id: "elena-rodriguez",
    name: "Elena Rodriguez",
    title: "Senior Architect",
    location: "Los Angeles, CA",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    rating: 4.9,
    reviewCount: 156,
    projectCount: 73,
    specialties: ["Luxury Residential", "Renovation", "Historic Preservation"],
    bio: "With a passion for blending old and new, I specialize in thoughtful renovations and luxury residential projects that honor architectural heritage while embracing modern living.",
    featured: true,
  },
  {
    id: "james-okonkwo",
    name: "James Okonkwo",
    title: "Founding Partner",
    location: "Chicago, IL",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    rating: 4.7,
    reviewCount: 94,
    projectCount: 55,
    specialties: ["Public Buildings", "Educational", "Community Spaces"],
    bio: "Dedicated to creating spaces that serve communities, my work focuses on public buildings, educational facilities, and spaces that bring people together.",
    featured: false,
  },
  {
    id: "ana-silva",
    name: "Ana Silva",
    title: "Lead Architect",
    location: "Miami, FL",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec8?w=800&h=600&fit=crop",
    rating: 4.8,
    reviewCount: 78,
    projectCount: 41,
    specialties: ["Coastal Architecture", "Resort Design", "Landscape"],
    bio: "Inspired by coastal landscapes and tropical environments, I create architecture that celebrates natural light, ocean views, and indoor-outdoor living.",
    featured: false,
  },
  {
    id: "david-kim",
    name: "David Kim",
    title: "Principal Designer",
    location: "Seattle, WA",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    rating: 4.9,
    reviewCount: 112,
    projectCount: 67,
    specialties: ["Tech Offices", "Minimalist", "Smart Homes"],
    bio: "At the intersection of technology and design, I create spaces that embrace innovation while maintaining warmth and human connection.",
    featured: true,
  },
]

export const portfolioProjects = [
  {
    id: "coastal-retreat",
    title: "Coastal Retreat",
    architect: "Sarah Chen",
    architectId: "sarah-chen",
    category: "Residential",
    location: "Malibu, CA",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    likes: 1284,
    views: 15420,
    description: "A stunning oceanfront residence that seamlessly blends indoor and outdoor living spaces.",
  },
  {
    id: "urban-loft",
    title: "Urban Loft Conversion",
    architect: "Marcus Weber",
    architectId: "marcus-weber",
    category: "Interior",
    location: "Brooklyn, NY",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    likes: 892,
    views: 11230,
    description: "An industrial warehouse transformed into a sophisticated living space with modern amenities.",
  },
  {
    id: "hillside-villa",
    title: "Hillside Villa",
    architect: "Elena Rodriguez",
    architectId: "elena-rodriguez",
    category: "Residential",
    location: "Los Angeles, CA",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    likes: 2156,
    views: 28940,
    description: "A luxurious hillside residence featuring panoramic views and sustainable design elements.",
  },
  {
    id: "tech-campus",
    title: "Innovation Campus",
    architect: "David Kim",
    architectId: "david-kim",
    category: "Commercial",
    location: "Seattle, WA",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
    likes: 1567,
    views: 19870,
    description: "A forward-thinking tech campus designed to foster collaboration and innovation.",
  },
  {
    id: "community-center",
    title: "Community Arts Center",
    architect: "James Okonkwo",
    architectId: "james-okonkwo",
    category: "Public",
    location: "Chicago, IL",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
    likes: 743,
    views: 8920,
    description: "A vibrant community space that brings together art, education, and social gathering.",
  },
  {
    id: "beach-house",
    title: "Tropical Beach House",
    architect: "Ana Silva",
    architectId: "ana-silva",
    category: "Residential",
    location: "Miami, FL",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600573472591-ee6c563aaec8?w=800&h=600&fit=crop",
    likes: 1823,
    views: 22450,
    description: "A tropical paradise featuring open-air living and seamless beach access.",
  },
  {
    id: "boutique-hotel",
    title: "Boutique Hotel",
    architect: "Elena Rodriguez",
    architectId: "elena-rodriguez",
    category: "Commercial",
    location: "Santa Barbara, CA",
    year: "2023",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
    likes: 1456,
    views: 17890,
    description: "A boutique hotel that captures the essence of California coastal elegance.",
  },
  {
    id: "minimalist-home",
    title: "Minimalist Sanctuary",
    architect: "David Kim",
    architectId: "david-kim",
    category: "Residential",
    location: "Portland, OR",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
    likes: 2089,
    views: 25670,
    description: "A serene minimalist home designed for mindful living and connection with nature.",
  },
  {
    id: "garden-renovation",
    title: "Garden Terrace House",
    architect: "Sarah Chen",
    architectId: "sarah-chen",
    category: "Renovation",
    location: "San Francisco, CA",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&h=600&fit=crop",
    likes: 967,
    views: 12340,
    description: "A thoughtful renovation that transforms a Victorian home with modern garden spaces.",
  },
  {
    id: "lakeside-cabin",
    title: "Lakeside Cabin",
    architect: "Marcus Weber",
    architectId: "marcus-weber",
    category: "Residential",
    location: "Lake Tahoe, CA",
    year: "2024",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    likes: 1678,
    views: 20150,
    description: "A modern interpretation of the classic mountain cabin with stunning lake views.",
  },
  {
    id: "urban-park",
    title: "Urban Pocket Park",
    architect: "James Okonkwo",
    architectId: "james-okonkwo",
    category: "Landscape",
    location: "Chicago, IL",
    year: "2024",
    image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=800&h=600&fit=crop",
    likes: 534,
    views: 6780,
    description: "A small urban park that provides a green oasis in a dense city neighborhood.",
  },
  {
    id: "spa-retreat",
    title: "Wellness Spa Resort",
    architect: "Ana Silva",
    architectId: "ana-silva",
    category: "Commercial",
    location: "Palm Beach, FL",
    year: "2023",
    image: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&h=600&fit=crop",
    likes: 1234,
    views: 15670,
    description: "A luxury wellness spa designed to promote relaxation and rejuvenation.",
  },
]

export const architectBids = [
  {
    id: "arch-bid-1",
    projectId: "bid-1",
    architectId: "sarah-chen",
    architect: "Sarah Chen",
    architectImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    proposedBudget: "$950,000",
    proposedTimeline: "14 months",
    submittedDate: "2024-01-18",
    status: "Pending",
    message: "I would love to design your modern family home. With my experience in sustainable residential design, I can create a space that balances modern aesthetics with eco-friendly features. My approach would include passive solar design, natural ventilation, and high-quality materials.",
    rating: 4.9,
    projectsCompleted: 48,
  },
  {
    id: "arch-bid-2",
    projectId: "bid-1",
    architectId: "david-kim",
    architect: "David Kim",
    architectImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    proposedBudget: "$1,050,000",
    proposedTimeline: "16 months",
    submittedDate: "2024-01-20",
    status: "Pending",
    message: "Your project aligns perfectly with my expertise in smart home integration and minimalist design. I envision a home that seamlessly integrates technology while maintaining warmth and connection to nature.",
    rating: 4.9,
    projectsCompleted: 67,
  },
  {
    id: "arch-bid-3",
    projectId: "bid-1",
    architectId: "marcus-weber",
    architect: "Marcus Weber",
    architectImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    proposedBudget: "$1,100,000",
    proposedTimeline: "15 months",
    submittedDate: "2024-01-19",
    status: "Pending",
    message: "I bring extensive experience in creating functional yet beautiful living spaces. My design would focus on flexible spaces that grow with your family while incorporating the latest in sustainable building practices.",
    rating: 4.8,
    projectsCompleted: 62,
  },
  {
    id: "arch-bid-4",
    projectId: "bid-2",
    architectId: "elena-rodriguez",
    architect: "Elena Rodriguez",
    architectImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    proposedBudget: "$195,000",
    proposedTimeline: "5 months",
    submittedDate: "2024-01-22",
    status: "Pending",
    message: "I specialize in luxury hospitality design and have completed several award-winning restaurant projects. My coastal modern approach would create an unforgettable dining atmosphere.",
    rating: 4.9,
    projectsCompleted: 73,
  },
  {
    id: "arch-bid-5",
    projectId: "bid-2",
    architectId: "ana-silva",
    architect: "Ana Silva",
    architectImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    proposedBudget: "$210,000",
    proposedTimeline: "5 months",
    submittedDate: "2024-01-23",
    status: "Pending",
    message: "Coastal architecture is my passion. I would bring a fresh perspective to your seafood restaurant with natural materials, ocean-inspired colors, and thoughtful lighting design.",
    rating: 4.8,
    projectsCompleted: 41,
  },
  {
    id: "arch-bid-6",
    projectId: "bid-3",
    architectId: "elena-rodriguez",
    architect: "Elena Rodriguez",
    architectImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    proposedBudget: "$620,000",
    proposedTimeline: "10 months",
    submittedDate: "2024-01-15",
    status: "Shortlisted",
    message: "Historic preservation is a core part of my practice. I have successfully completed numerous projects that honor original architectural details while seamlessly integrating modern amenities.",
    rating: 4.9,
    projectsCompleted: 73,
  },
  {
    id: "arch-bid-7",
    projectId: "bid-4",
    architectId: "david-kim",
    architect: "David Kim",
    architectImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop",
    proposedBudget: "$380,000",
    proposedTimeline: "7 months",
    submittedDate: "2024-01-24",
    status: "Pending",
    message: "Tech office design is my specialty. I understand the unique needs of creative agencies and would design spaces that foster collaboration, focus, and innovation.",
    rating: 4.9,
    projectsCompleted: 67,
  },
  {
    id: "arch-bid-8",
    projectId: "bid-5",
    architectId: "ana-silva",
    architect: "Ana Silva",
    architectImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
    proposedBudget: "$1,750,000",
    proposedTimeline: "20 months",
    submittedDate: "2024-01-25",
    status: "Pending",
    message: "Beachfront luxury homes are my expertise. I would create a stunning retreat that maximizes ocean views while ensuring privacy and sustainability.",
    rating: 4.8,
    projectsCompleted: 41,
  },
  {
    id: "arch-bid-9",
    projectId: "bid-5",
    architectId: "sarah-chen",
    architect: "Sarah Chen",
    architectImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    proposedBudget: "$1,850,000",
    proposedTimeline: "22 months",
    submittedDate: "2024-01-26",
    status: "Pending",
    message: "Sustainable coastal design is at the heart of my practice. I would design a home that respects the oceanfront environment while delivering the luxury and comfort you desire.",
    rating: 4.9,
    projectsCompleted: 48,
  },
]

export const projectBids = [
  {
    id: "bid-1",
    projectTitle: "Modern Family Home",
    projectType: "Residential",
    client: "Thompson Family",
    budget: "$850,000 - $1,200,000",
    timeline: "12-18 months",
    location: "Palo Alto, CA",
    description: "Looking for an architect to design a 4-bedroom modern family home with sustainable features, home office space, and indoor-outdoor living areas.",
    postedDate: "2024-01-15",
    deadline: "2024-02-15",
    bidsReceived: 8,
    status: "Open",
  },
  {
    id: "bid-2",
    projectTitle: "Restaurant Interior Redesign",
    projectType: "Commercial",
    client: "Blue Ocean Hospitality",
    budget: "$150,000 - $250,000",
    timeline: "4-6 months",
    location: "San Diego, CA",
    description: "Complete interior redesign of a 3,500 sq ft upscale seafood restaurant. Looking for a fresh, coastal modern aesthetic.",
    postedDate: "2024-01-18",
    deadline: "2024-02-20",
    bidsReceived: 12,
    status: "Open",
  },
  {
    id: "bid-3",
    projectTitle: "Historic Home Renovation",
    projectType: "Renovation",
    client: "Private Client",
    budget: "$500,000 - $750,000",
    timeline: "8-12 months",
    location: "Boston, MA",
    description: "Seeking an architect experienced in historic preservation to renovate a 1920s colonial home while adding modern amenities.",
    postedDate: "2024-01-10",
    deadline: "2024-02-10",
    bidsReceived: 5,
    status: "Under Review",
  },
  {
    id: "bid-4",
    projectTitle: "Boutique Office Space",
    projectType: "Commercial",
    client: "Creative Studios Inc.",
    budget: "$300,000 - $450,000",
    timeline: "6-9 months",
    location: "Austin, TX",
    description: "Design a creative office space for a 50-person design agency. Focus on collaboration areas, quiet zones, and unique meeting spaces.",
    postedDate: "2024-01-20",
    deadline: "2024-02-25",
    bidsReceived: 15,
    status: "Open",
  },
  {
    id: "bid-5",
    projectTitle: "Beach Vacation Home",
    projectType: "Residential",
    client: "Martinez Family",
    budget: "$1,500,000 - $2,000,000",
    timeline: "18-24 months",
    location: "Malibu, CA",
    description: "Luxury beachfront vacation home with 5 bedrooms, infinity pool, and guest house. Sustainability and ocean views are priorities.",
    postedDate: "2024-01-22",
    deadline: "2024-03-01",
    bidsReceived: 20,
    status: "Open",
  },
]
